[package]
name = "puzzle_15b"
version.workspace = true
authors.workspace = true
description = "Puzzle 15B"
edition.workspace = true

[[bin]]
name = "puzzle_15b"
path = "src/puzzle_15b.rs"

[dependencies]
nom = { workspace = true }
