[package]
name = "puzzle_5a"
version.workspace = true
authors.workspace = true
description = "Puzzle 5A"
edition.workspace = true

[[bin]]
name = "puzzle_5a"
path = "src/puzzle_5a.rs"

[dependencies]
nom = { workspace = true }
