[package]
name = "puzzle_7a"
version.workspace = true
authors.workspace = true
description = "Puzzle 7A"
edition.workspace = true

[[bin]]
name = "puzzle_7a"
path = "src/puzzle_7a.rs"

[dependencies]
nom = { workspace = true }
