[package]
name = "puzzle_18b"
version.workspace = true
authors.workspace = true
description = "Puzzle 18B"
edition.workspace = true

[[bin]]
name = "puzzle_18b"
path = "src/puzzle_18b.rs"

[dependencies]
nom = { workspace = true }
rayon = { workspace = true }
