[package]
name = "puzzle_20a"
version.workspace = true
authors.workspace = true
description = "Puzzle 20A"
edition.workspace = true

[[bin]]
name = "puzzle_20a"
path = "src/puzzle_20a.rs"

[dependencies]
nom = { workspace = true }
