[package]
name = "puzzle_1a"
version.workspace = true
authors.workspace = true
description = "Puzzle 1A"
edition.workspace = true

[[bin]]
name = "puzzle_1a"
path = "src/puzzle_1a.rs"

[dependencies]
