[package]
name = "puzzle_18a"
version.workspace = true
authors.workspace = true
description = "Puzzle 18A"
edition.workspace = true

[[bin]]
name = "puzzle_18a"
path = "src/puzzle_18a.rs"

[dependencies]
nom = { workspace = true }
