[package]
name = "puzzle_6b"
version.workspace = true
authors.workspace = true
description = "Puzzle 6B"
edition.workspace = true

[[bin]]
name = "puzzle_6b"
path = "src/puzzle_6b.rs"

[dependencies]
nom = { workspace = true }
