[package]
name = "puzzle_2b"
version.workspace = true
authors.workspace = true
description = "Puzzle 1B"
edition.workspace = true

[[bin]]
name = "puzzle_2b"
path = "src/puzzle_2b.rs"

[dependencies]
